Console.BackgroundColor =ConsoleColor.Blue;
Console.ForegroundColor =ConsoleColor.Magenta;
Console.WriteLine("Faded-Alan Walker");
Console.ResetColor();
Console.WriteLine();
Console.WriteLine("You were the shadow to my light");
Console.WriteLine("Did you feel us?");
Console.WriteLine("Another star, you fade away");
Console.WriteLine("Afraid our aim is out of sight");
Console.WriteLine("Wanna see us alive");
Console.WriteLine();
Console.WriteLine("Where are you now?");
Console.WriteLine("Where are you now?");
Console.WriteLine("Where are you now?");
Console.WriteLine("Was it all in my fantasy?");
Console.WriteLine("Where are you now?");
Console.WriteLine("Were you only imaginary?");
Console.WriteLine();
Console.WriteLine("Where are you now?");
Console.WriteLine("Atlantis, under the sea, under the sea");
Console.WriteLine("Where are you now? Another dream");
Console.WriteLine("The monster's running wild inside of me");
Console.WriteLine();
Console.WriteLine("I'm faded, I'm faded");
Console.WriteLine("So lost, I'm faded, I'm faded");
Console.WriteLine("So lost, I'm faded");
Console.WriteLine();
Console.WriteLine("These shallow waters never met what I needed");
Console.WriteLine("I'm letting go, a deeper dive");
Console.WriteLine("Eternal silence of the sea");
Console.WriteLine("I'm breathing, alive");
Console.WriteLine();
Console.WriteLine("Where are you now?");
Console.WriteLine("Where are you now?");
Console.WriteLine("Under the bright but faded lights");
Console.WriteLine("Where are you now?");
Console.WriteLine("Where are you now?");
Console.WriteLine();
Console.WriteLine("Where are you now?");
Console.WriteLine("Atlantis, under the sea, under the sea");
Console.WriteLine("Where are you now? Another dream");
Console.WriteLine("The monster's running wild inside of me");
Console.WriteLine("I'm faded, I'm faded");
Console.WriteLine("So lost, I'm faded, I'm faded");
Console.WriteLine("So lost, I'm faded");
